repository: lmarangio/lmarangio.github.io

layout: sidebar # sidebar | stacked
style: dark # light | dark

plugins:
  # GitHub Pages plugins
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jemoji

  # Other plugins
  - jekyll-get-json

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

updates:
  limit: 8
  news:
    - date: '29/05/2023'
      content: 'Pushed my firsts Q# algorithms.'    
    - date: '24/05/2023'
      content: 'Got certification in Digital Fashion Innovation Specialization, Coursera'  
    - date: '15/03/2023'
      content: 'Start working at Esprit as Integrations Engineer'
    - date: '01/03/2022'
      content: 'Start working at Channable as Integrations Engineer'
    - date: '15/11/2021'
      content: 'Start working at Randstad as Algorithm Developer (Python)'
    - date: '11/2021'
      content: 'Google Data Analytics Professional Certification, Ask Questions to Make Data-Driven Decisions'
    - date: '11/2021'
      content: 'Google Data Analytics Professional Certification, Foundations: Data, Data, Everywhere'
    - date: '31/10/2021'
      content: 'New paper coming up: A posteriori validated numerical method for the computation of stationary measures based on Fourier approximation.'
    - date: '5/10/2021'
      content: 'My first author article on the Arnold maps, has been cited in the 2021 Physics Nobel prize literature.'
    - date: '01/06/2021'
      content: 'Started Math Research position at Mathematics department in Pisa, Italy.'
    - date: '27/04/2021'
      content: 'Defended Ph.D. Thesis at the Pisa/Bourgogne Franche-Comté University.'

awards:
  - honorary
  - brazil
  - vinci

talks:
  - sec19
  - beyond
  - CSM18
  - Mena18
  - Seq18

publications:
  - year: 2021
    pubs:
      - fourier
      - lda
      - thesis
  - year: 2019
    pubs:
      - arnold
      - garbo
  - year: 2018
    pubs:
      - lib
      - ieee18

projects:
  sort_by: stars # pushed | stars
  limit: 10
  exclude:
    archived: false
    forks: false
    projects:
      - lmarangio.github.io
  external: # static repo jsons in _data/projects.yml
    projects:
      - tma

#Repositories not owned by me
jekyll_get_json:
  - data: gtolias/tma
  - json: 'https://api.github.com/repos/gtolias/tma'

social_media:
  googlescholar: YE9A7UEAAAAJ
  github: lmarangio

social_media_short:
  researchgate: Luigi-Marangio
  linkedin: lmarangio

# topics:
#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
