repository: lmarangio/lmarangio.github.io

layout: sidebar # sidebar | stacked
style: dark # light | dark

plugins:
  # GitHub Pages plugins
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jemoji

  # Other plugins
  - jekyll-get-json

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

updates:
  limit: 5
  news:
    - date: '31/10/2021'
      content: 'New paper coming up: A posteriori validated numerical method for the computation of stationary measures based on Fourier approximation.'
    - date: '01/06/2021'
      content: 'Started Math Research position at Mathematics department in Pisa, Italy.'
    - date: '27/04/2021'
      content: 'Defended Ph.D. Thesis at the Pisa/Bourgogne Franche-Comté University.'

awards:
  - reviewer
  - ctu19
  - cski19
  - feectu19
  # - cvww18
  - ucg12
  - ikcg12
  - epcg11
  - podgorica10
  - canu10
  - etfucg

talks:
  - fhua18
  - mlmu17
  - mlpw17
  - prcvc15

publications:
  - year: 2021
    pubs:
      # - dtp+21
      - rsg+21
  - year: 2020
    pubs:
      - grb20
  - year: 2019
    pubs:
      - r19
      - trc19
      - rtc19
  - year: 2018
    pubs:
      - rtc18
      - rit+18
      - mrm18
  - year: 2017
    pubs:
      - mmrm17
  - year: 2016
    pubs:
      - rtc16
      - rsj+16
  - year: 2015
    pubs:
      - rjc15
      - srcf15
      - shr+15
      - cvh+15
  - year: 2014
    pubs:
      - mrcm14
  - year: 2013
    pubs:
      - spr13
      - prs13

projects:
  sort_by: stars # pushed | stars
  limit: 10
  exclude:
    archived: false
    forks: false
    projects:
      - lmarangio.github.io
  external: # static repo jsons in _data/projects.yml
    projects:
      - tma

#Repositories not owned by me
jekyll_get_json:
  - data: gtolias/tma
  - json: 'https://api.github.com/repos/gtolias/tma'

social_media:
  googlescholar: YE9A7UEAAAAJ
  github: lmarangio

social_media_short:
  researchgate: Luigi Marangio
  linkedin: lmarangio

# topics:
#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
